apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: chat-app
    component: mongodb
spec:
  selector:
    matchLabels:
      app: chat-app
      component: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chat-app
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: chat-app
    component: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: chat-app
    component: mongodb