apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: chat-app
    component: redis
spec:
  selector:
    matchLabels:
      app: chat-app
      component: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-app
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 256Mi
            cpu: 300m
          requests:
            memory: 128Mi
            cpu: 150m
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: chat-app
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: chat-app
    component: redis