services:
  frontendA:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USER_ID=A
      - REACT_APP_BACKEND_HOST=backend
    depends_on:
      - backend
    image: chat-app-frontend-a

  frontendB:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_USER_ID=B
      - REACT_APP_BACKEND_HOST=backend
    depends_on:
      - backend
    image: chat-app-frontend-b

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    image: chat-app-backend
